/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SenggolUKT;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User ID
 */
public class Data extends javax.swing.JFrame {

    private Object tname;


    /**
     * Creates new form TA_PDKP
     */
    public Data() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        judul = new javax.swing.JLabel();
        nim = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jalur = new javax.swing.JLabel();
        apa = new javax.swing.JLabel();
        ortu = new javax.swing.JLabel();
        tnama = new javax.swing.JTextField();
        tnim = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        snm = new javax.swing.JRadioButton();
        sbm = new javax.swing.JRadioButton();
        sbub = new javax.swing.JRadioButton();
        um = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        ya = new javax.swing.JCheckBox();
        tdk = new javax.swing.JCheckBox();
        comboortu = new javax.swing.JComboBox<>();
        proses = new javax.swing.JButton();
        salah = new javax.swing.JButton();
        nama1 = new javax.swing.JLabel();
        nim1 = new javax.swing.JLabel();
        jalur1 = new javax.swing.JLabel();
        lbnama = new javax.swing.JLabel();
        lbnim = new javax.swing.JLabel();
        lbjalur = new javax.swing.JLabel();
        benar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_mhs = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbgol = new javax.swing.JLabel();
        lbukt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        judul.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 24)); // NOI18N
        judul.setText("SISTEM PENENTUAN GOLONGAN UKT FAKULTAS TEKNIK UNDIP");
        getContentPane().add(judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 550, 70));

        nim.setText("NIM");
        getContentPane().add(nim, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 181, 133, 31));

        nama.setText("Nama");
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 133, 31));

        jalur.setText("Jalur Masuk ");
        getContentPane().add(jalur, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 133, 31));

        apa.setText("Apakah anda mahasiswa bidikmisi?");
        getContentPane().add(apa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 260, 31));

        ortu.setText("Penghasilan orang tua per bulan");
        getContentPane().add(ortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 232, 31));
        getContentPane().add(tnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 296, -1));
        getContentPane().add(tnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 296, -1));

        buttonGroup1.add(snm);
        snm.setText("SNMPTN");
        snm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                snmActionPerformed(evt);
            }
        });

        buttonGroup1.add(sbm);
        sbm.setText("SBMPTN");
        sbm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbmActionPerformed(evt);
            }
        });

        buttonGroup1.add(sbub);
        sbub.setText("SBUB");
        sbub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbubActionPerformed(evt);
            }
        });

        buttonGroup1.add(um);
        um.setText("Ujian Mandiri");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(snm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sbm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(sbub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(um, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(snm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sbub)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(um)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 296, -1));

        buttonGroup2.add(ya);
        ya.setText("Ya");

        buttonGroup2.add(tdk);
        tdk.setText("Tidak");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ya)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 174, Short.MAX_VALUE)
                .addComponent(tdk))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tdk)
                .addComponent(ya))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 296, -1));

        comboortu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< Rp500.000", "Rp500.001 - Rp1.500.000", "Rp1.500.001 - Rp3.000.000", "Rp3.000.001 - Rp4.500.000", "Rp4.500.001 - Rp6.000.000", "Rp6.000.001 - Rp7.000.000", "> Rp7.000.000" }));
        comboortu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboortuActionPerformed(evt);
            }
        });
        getContentPane().add(comboortu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 296, -1));

        proses.setText("PROSES");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses, new org.netbeans.lib.awtextra.AbsoluteConstraints(261, 466, -1, -1));

        salah.setText("SALAH");
        salah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salahActionPerformed(evt);
            }
        });
        getContentPane().add(salah, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 720, -1, -1));

        nama1.setText("Nama");
        getContentPane().add(nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 133, 31));

        nim1.setText("NIM");
        getContentPane().add(nim1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 133, 31));

        jalur1.setText("Jalur Masuk ");
        getContentPane().add(jalur1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 133, 31));

        lbnama.setText("-");
        getContentPane().add(lbnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 530, -1, -1));

        lbnim.setText("-");
        getContentPane().add(lbnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 570, -1, -1));

        lbjalur.setText("-");
        getContentPane().add(lbjalur, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 610, -1, -1));

        benar.setText("BENAR");
        benar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benarActionPerformed(evt);
            }
        });
        getContentPane().add(benar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 720, -1, -1));

        tbl_mhs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "NIM", "Jalur Masuk", "Golongan", "Jumlah UKT"
            }
        ));
        jScrollPane1.setViewportView(tbl_mhs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 550, 580));

        jLabel1.setText("Golongan ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, -1, -1));

        jLabel2.setText("Jumlah UKT per semester");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, -1, -1));

        lbgol.setText("-");
        getContentPane().add(lbgol, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 640, 168, -1));

        lbukt.setText("-");
        getContentPane().add(lbukt, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 670, 188, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/2020-05-14 10.46.06 1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 780, 640));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iutiiy.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 440));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iutiiy.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 620, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iutiiy.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, 430));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/iutiiy.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 340, 620, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
    
    }//GEN-LAST:event_umActionPerformed

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
    String name = tnama.getText();
    lbnama.setText(name);
    String nims = tnim.getText();
    lbnim.setText(nims);
 
    String kode_jlr = (String)comboortu.getSelectedItem();
    if(kode_jlr == "< Rp500.000"){
        String gol = Integer.toString(1);
        String ukt = Integer.toString(500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "Rp500.001 - Rp1.500.000"){
        String gol = Integer.toString(2);
        String ukt = Integer.toString(1000000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "Rp1.500.001 - Rp3.000.000"){
        String gol = Integer.toString(3);
        String ukt = Integer.toString(2500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "Rp3.000.001 - Rp4.500.000"){
        String gol = Integer.toString(4);
        String ukt = Integer.toString(3500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "Rp4.500.001 - Rp6.000.000"){
        String gol = Integer.toString(5);
        String ukt = Integer.toString(4500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "Rp6.000.001 - Rp7.000.000"){
        String gol = Integer.toString(6);
        String ukt = Integer.toString(6000000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    else if(kode_jlr == "> Rp7.000.000"){
        String gol = Integer.toString(7);
        String ukt = Integer.toString(7500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }

    String jl;
    if(snm.isSelected()){
        jl = "SNMPTN";
        lbjalur.setText(jl);
    }
    else if (sbm.isSelected()){
        jl = "SBMPTN";
        lbjalur.setText(jl);
    }
    else if (sbub.isSelected()){
        jl = "SBUB";
        lbjalur.setText(jl);
    }
    else if (um.isSelected()){
        jl = "Ujian Mandiri";
        lbjalur.setText(jl);
        String gol = Integer.toString(7);
        String ukt = Integer.toString(7500000);
        lbgol.setText(gol);
        lbukt.setText(ukt);
    }
    String bm;
    if(ya.isSelected()){
        bm = "Bidikmisi";
        String ukt = Integer.toString(0);
        lbgol.setText(bm);
        lbukt.setText(ukt);
    }
    }//GEN-LAST:event_prosesActionPerformed

    private void snmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_snmActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_snmActionPerformed

    private void sbmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbmActionPerformed

    }//GEN-LAST:event_sbmActionPerformed

    private void sbubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbubActionPerformed

    }//GEN-LAST:event_sbubActionPerformed

    private void comboortuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboortuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboortuActionPerformed

    private void salahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salahActionPerformed
    tnama.setText("");
    tnim.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    ya.setSelected(false);
    tdk.setSelected(false);
    lbnama.setText("-");
    lbnim.setText("-");
    lbjalur.setText("-");
    lbgol.setText("-");
    lbukt.setText("-");// TODO add your handling code here:
    }//GEN-LAST:event_salahActionPerformed

    private void benarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_benarActionPerformed
    DefaultTableModel model= (DefaultTableModel) tbl_mhs.getModel();
    model.addRow(new Object[]{lbnama.getText(),lbnim.getText(),lbjalur.getText(),lbgol.getText(),lbukt.getText()});
    tnama.setText("");
    tnim.setText("");
    buttonGroup1.clearSelection();
    buttonGroup2.clearSelection();
    ya.setSelected(false);
    tdk.setSelected(false);
    lbnama.setText("-");
    lbnim.setText("-");
    lbjalur.setText("-");
    lbgol.setText("-");
    lbukt.setText("-");
    }//GEN-LAST:event_benarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apa;
    private javax.swing.JButton benar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> comboortu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jalur;
    private javax.swing.JLabel jalur1;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel lbgol;
    private javax.swing.JLabel lbjalur;
    private javax.swing.JLabel lbnama;
    private javax.swing.JLabel lbnim;
    private javax.swing.JLabel lbukt;
    private javax.swing.JLabel nama;
    private javax.swing.JLabel nama1;
    private javax.swing.JLabel nim;
    private javax.swing.JLabel nim1;
    private javax.swing.JLabel ortu;
    private javax.swing.JButton proses;
    private javax.swing.JButton salah;
    private javax.swing.JRadioButton sbm;
    private javax.swing.JRadioButton sbub;
    private javax.swing.JRadioButton snm;
    private javax.swing.JTable tbl_mhs;
    private javax.swing.JCheckBox tdk;
    private javax.swing.JTextField tnama;
    private javax.swing.JTextField tnim;
    private javax.swing.JRadioButton um;
    private javax.swing.JCheckBox ya;
    // End of variables declaration//GEN-END:variables
}
